Update sonarqube_job.yaml

diff --git a/azure_devops/templates/sonarqube_job.yaml b/azure_devops/templates/sonarqube_job.yaml
--- a/azure_devops/templates/sonarqube_job.yaml
+++ b/azure_devops/templates/sonarqube_job.yaml
@@ -16,3 +16,14 @@ jobs:
           scannerMode: 'dotnet'
           projectKey: '${{parameters.projectKey}}'
           projectName: '${{parameters.projectName}}'
+
+      - bash: |
+          displayName: "Enforce Quality Gate"
+          echo "Quality Gate Status: $(SONARQUBEQUALITYGATESTATUS)"
+          if ["$(SONARQUBEQUALITYGATESTATUS)" != "passed" ]; then
+          echo "Quality Gate Failed - Failing Pipeline"
+          exit 1
+          else
+          echo "✅ Quality Gate Passed"
+          fi
+      
